name: eshop-front
namespace: eshop
replicas: 1
image: danieljaraba/eshop-front:49547651bc7516bf84fda8ad711e2c798acf8443
containerPort: 80
service:
  portname: http
  port: 80
  targetPort: 80

env:
  - name: VITE_API_URL
    value: http://localhost:8080
