name: eshop-front
namespace: eshop
replicas: 1
image: danieljaraba/eshop-front:22c8db7b6ee4a611aa5d1e863547b20e0ec0f86f
containerPort: 80
service:
  portname: http
  port: 80
  targetPort: 80

env:
  - name: VITE_API_URL
    value: http://localhost:8080
